---

- hosts: all
  become: true
  tasks:

  - name: Install Docker
    apt:
      state: latest

  - name: Enable Docker
    service:
      name: docker
      state: started
      enabled: true

  - name: Copy Docker
    copy: src=dockerfile

  - name: Build Docker
    docker_image:
      name: containeransible
      build:
        args:
          listen_ports: 8080
